<?php
/*
 * Template Name: エントリーフォーム
 */
get_header(); ?>

<main>
    <!-- Page Header -->
    <section class="page-header" style="height: 250px;">
        <div class="page-header-bg"
            style="background-image: url('<?php echo esc_url(get_template_directory_uri()); ?>/images/recruit_bg_new.png');">
        </div>
        <div class="page-header-overlay"
            style="background: linear-gradient(135deg, rgba(0, 0, 0, 0.6) 0%, rgba(203, 221, 0, 0.4) 100%);"></div>
        <div class="container text-center" style="z-index: 1;">
            <h2 class="page-title">エントリー<span class="ja">Entry</span></h2>
        </div>
    </section>

    <!-- Breadcrumbs -->
    <nav class="breadcrumbs">
        <div class="container">
            <ul>
                <li><a href="<?php echo esc_url(home_url('/')); ?>">Home</a></li>
                <li><i class="fa-solid fa-chevron-right"></i></li>
                <li><a href="<?php echo esc_url(home_url('/recruit/')); ?>">採用情報</a></li>
                <li><i class="fa-solid fa-chevron-right"></i></li>
                <li>エントリーフォーム</li>
            </ul>
        </div>
    </nav>

    <section class="section contact-section">
        <div class="container container-narrow">
            <div class="section-title">
                <span class="subtitle">Recruitment Entry</span>
                <h3>エントリーフォーム</h3>
                <p class="mt-4">
                    私たちと一緒に新しい介護の形を作りませんか？<br>
                    以下のフォームより必要事項をご記入の上、ご応募ください。<br>
                    まずは職場見学をしてみたい、という方も大歓迎です！（お電話 06-6643-3300 でも承っております）
                </p>
            </div>

            <div class="contact-form-wrapper mt-5">
                <!-- 
                    WordPress Contact Form 7 or MW WP Form Shortcode 
                    The ID should be replaced with the actual ID generated by the plugin.
                    For now, it's set as a standard CF7 shortcode placeholder.
                -->
                <?php echo do_shortcode('[contact-form-7 id="entry" title="エントリーフォーム"]'); ?>

                <!-- 
                Reference Original HTML structure for CF7 UI mapping:
                <div class="form-group row">
                    <label class="form-label col">お名前 <span class="required">必須</span></label>
                    <div class="form-control-wrap col">
                        [text* your-name class:form-control placeholder "例：山田 太郎"]
                    </div>
                </div>
                ...
                -->
            </div>
        </div>
    </section>

</main>

<?php get_footer(); ?>